version: 2.1
workflows:
  main:
    jobs:
      - unit-1_0:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - unit-1_1:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - unit-latest:
          coverage: true
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - build-docs:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - deploy-docs:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
          requires:
            - unit-latest
            - build-docs

job-references:
  env-1_0: &env-1_0
    docker:
      - image: julia:1.0

  env-1_1: &env-1_1
    docker:
      - image: julia:1.1

  env-latest: &env-latest
    docker:
      - image: julia:latest

  restore_julia: &restore_julia
    keys:
      - deps-

  install_julia: &install_julia
    name: Install Julia dependencies
    command: julia --project -e 'using Pkg; Pkg.instantiate();'

  save_julia: &save_julia
    key: deps-
    paths:
      - ~/.julia/compiled
      - ~/.julia/packages
      - ~/.julia/registries

  restore_julia_in_docs: &restore_julia_in_docs
    keys:
      - deps-{{ checksum "docs/Project.toml" }}
      - deps-

  install_julia_in_docs: &install_julia_in_docs
    name: Install Julia dependencies
    command: |
      cp docs/Project.toml docs/Project.toml.old
      julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'

  save_julia_in_docs: &save_julia_in_docs
    key: deps-{{ checksum "docs/Project.toml.old" }}
    paths:
      - ~/.julia/compiled
      - ~/.julia/packages
      - ~/.julia/registries

  unit: &unit
    parameters:
      coverage:
        type: boolean
        default: false
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia
      - run: *install_julia
      - save_cache: *save_julia

      - run:
          name: Run Tests
          command: julia --project -e 'using Pkg; Pkg.test(; coverage = true);'
      - when:
          condition: <<parameters.coverage>>
          steps:
            - run:
                name: Upload Coverage Results
                command: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'

jobs:
  unit-1_0:
    <<: *env-1_0
    <<: *unit

  unit-1_1:
    <<: *env-1_1
    <<: *unit

  unit-latest:
    <<: *env-latest
    <<: *unit

  build-docs:
    <<: *env-latest
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia_in_docs
      - run: *install_julia_in_docs
      - save_cache: *save_julia_in_docs

      - run:
          name: Build documentation
          command: julia --project=docs/ docs/make.jl
      - persist_to_workspace:
          root: docs/build
          paths:
            - "*"
      - run:
          name: Compress Artifacts
          command: tar -cvf docs.tar docs/build
      - store_artifacts:
          path: docs.tar
  deploy-docs:
    <<: *env-latest
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia_in_docs
      - run: *install_julia_in_docs
      - save_cache: *save_julia_in_docs

      - attach_workspace:
          at: docs/build
      - run:
          name: Deploy documentation to GitHub pages
          command: julia --project=docs/ docs/deploy.jl
